# globals.py
from pathlib import Path
from typing import Dict, List
import polars as pl
from pathlib import Path
from typing import Dict, List, Optional, Any

ROOT_PATH = Path(
    r"\\sia\AECF\DGATIC\LOTA\Bases de Datos\SIGER")

TABLES_TO_PROCESS = [
    'BTSOLICITUDES',
    # 'BTSOLICITUDES', 'CFVARIABLES', 'CTACCION', 'CTACTOS', 'CTCONDONACIONES',
    # 'CTESTADOS', 'CTESTADOSACTO', 'CTESTATUS', 'CTESTATUSCARATULA',
    # 'CTESTATUSFEDA', 'CTFEDATARIOS', 'CTGIROS', 'CTMUNICIPIOS',
    # 'CTNACIONALIDADES', 'CTOFICINAS', 'CTSOCIOS', 'CTTIPOSOCIEDAD',
    # 'CTUSUARIOS_202511281728', 'DTCOMPSOCIOS',  'MVCARATULAS',
    # 'MVFRMACTO', 'MVSOLICITUDES', 'MVVARACTO', 'PAGO_PORTAL',
]

# Tables with '"' inside the cells
quote_char_double_quotes = ['MVCARATULAS', 'MVFRMACTO', 'MVSOLICITUDES',
                            'CTUSUARIOS_202511281728', 'PAGO_PORTAL']

# Tables with encoding='utf8-lossy'
TABLES_UTF8 = ['CTUSUARIOS_202511281728', 'MVCARATULAS', 'MVSOLICITUDES']

# Tables with columns to be renamed
table_with_column_rename = ['MVFRMACTO']

# Column to be renamed, "_MVFRMACTO" is added to the column name
col_rename = 'DSACTO'

# Columns with very long data
LONG_TEXT_COLS = ['DSDOMICILIO']

# Columns to be dropped
col_drop = [
    'CRFME', 'DSANTREG', 'CFPAGODERECHOS_LLOFICINA', 'FULTLOGIN', 'DSCORREO',
    'FCNACIMIENTO', 'BLFOTO', 'DSADSCRIPCION', 'DSCONTRASENIA', 'DSACTO_MVFRMACTO',
    'NOCONSECUTIVO', 'NORENGLON', 'NOMONTO', 'LLGRUPOTRABAJO', 'DSNOMBRERESPOFIC',
    'NOCONTINUIDAD', 'DSOBSERVACIONES', 'LLENTREGA', 'LLTIPOACLARACION', 'LLTIPOACTO',
    'LLPAGOSSINREG', 'LLSOLINSCRIPCION', 'LLSOLICITUD_2', 'LLPAGOSSRPETUSU',
    'FCLIMITESUBS', 'DSTELEFONO', 'DSFEA', 'DSMIMETYPEFOTO', 'FCREACTIVACION',
    'CRCODCONFIRMACION', 'DSJUSTIFICACION', 'NOINTLOGIN', 'DSTELCONTACTO',
    'FCACTUALIZCONTRAS', 'FCULTINTLOGIN', 'DSEXTENCION', 'LLOFICINAMG', 'LLESTADOADS',
    'DSPAGINAWEB', 'LLPROCESO', 'DSREFERENCIARQ', 'NOTXCOUNTRQ', 'DSEXTENCION',
    'DSCONCEPTORQ', 'DSRFCRQ', 'DSCLAVEMUNICIPIORQ', 'NOMOVIMIENTOSRQ', 'LLCTFRMPRE',
    'DSACTORQ', 'DSDOMICILIORQ', 'DSENTIDADRQ', 'DSMUNICIPIORQ', 'DSCURP',
    'DSCPRQ', 'DSTELEFONORQ', 'DSIDNOTARIORQ', 'DSNOMBRENOTARIORQ', 'FCLIMITE',
    'DSRFCNOTARIORQ', 'DSTXIDRQ', 'DSNOMBRENOTARIORQ', 'DSFEDANETRQ', 'DSMOTIVO',
    'DSTELEFONONOTARIORQ', 'DSMAILNOTARIORQ', 'DSCUENTARQ', 'DSPASSWORDRQ',
    'NOSERVICIOIDRQ', 'DSNOMBRERQ', 'DSAPELLIDOPATERNORQ', 'DSAPELLIDOMATERNORQ',
    'DSRAZONSOCIALRQ', 'DSTRAMITERQ', 'DSTIPOPAGORS', 'DSACTOCORTA', 'DSPAIS',
    'DSCONCEPTORS', 'DSNOTARIORS', 'DSFOLIORS', 'DSCLAVEGIRO', 'NOCONSECUTIVO',
    'LLMUNICIPIOADS', 'LLETAPA', 'LLPAGODERECHO', 'LLTIPOFEDATARIO'
]

# Columns 'Int32' type for all tables
col_int32 = [
    'LLBTSOLICITUD', 'LLUSUARIO', 'LLGRUPOTRABAJO', 'LLESTATUS', 'LLPADRETIPSOC',
    'LLCARATULA', 'LLOFICINA', 'LLMUNICIPIO', 'LLSOCIO', 'LLESTADO', 'NONIVEL',
    'LLGIRO', 'LLTIPOSOCIEDAD', 'LLVARIABLE', 'LLNACIONALIDAD', 'LLESTATUSUSUA',
    'LLESTATUSCARATULA', 'LLPAGODERECHO', 'LLMVFRMACTO', 'LLSOLFRMPRE', 'LLCOMPSOCIOS',
    'LLESTDOACTO', 'LLFORMAACTO', 'LLVARACTO', 'LLTIPOSOLICITUD', 'LLFEDATARIO',
    'LLCOMPFEDA', 'LLSOLICITUD', 'LLPAGO', 'LLACTO', 'LLMUNICIPIOADS',
    'LLESTATUSBANDEJA', 'LLUSOHORARIO', 'LLOFICINAMG', 'LLTIPOACTO', 'LLACCION',
    'LLCTFRMPRE', 'LLESTATUSFEDA', 'LLTIPOFEDATARIO', 'CRNUMERO', 'LLESTADOADS',
    'LLINFFRMPRE', 'LLESTDOACTOPRE', 'LLMVFRMACTOSUB',
]

# Columns 'Boolean' type for all tables
col_Boolean = ['BOMORAL', 'BOACERVO', 'BOACTIVO', 'BOVARIABLERANGO', 'BOANOTACIONACTIVA',
               'BOMIGRACION', 'BOINGRESO', 'BOINCIDENCIAS', 'BOPERNOSUBS', 'BOABREFOLIO',
               'BOVISIBLE', 'BOESFEDATARIO']

# Columns 'DATE' type for all tables
col_date = ['FCETAPA', 'FCAPERTURA', 'FCNACIMIENTO',
            'FULTLOGIN', 'FCTRANSACCIONRS']

# String Columns to be converted to string, to be clean and to be converted to uppercase
col_str = ['DSDENSOCIAL', 'DSDIRECCION', 'DSDURACION', 'DSNOMBRESOCIO', 'DSRFC',
           'DSGIRO', 'DSTIPOSOCIEDAD', 'DSOBJETO', 'DSAPELLIDOPATERNO', 'DSESTADO',
           'DSNACIONALIDAD', 'DSAPELLIDOMATERNO', 'DSNOMBREVARIABLE', 'DSCODIGO',
           'DSDESCRIPCION', 'DSNOMBRE', 'DSOFICINA', 'DSMUNICIPIO', 'DSACTO', 'DSSERIE',
           'DSACCION', 'DSNOMBRECOND', 'DSESTADOACTO', 'DSESTATUS', 'DSABREVSTATUS',
           'FCMODIFICACION', 'FCCONSTITUCION', 'DSDOMICILIO', 'FCINGRESO', 'FCALTA',
           'FCINSCRIPCION', 'DSNOMBRERESP', 'FCINIOPERACION']

# Primary keys of every table
primary_keys = {
    'BTSOLICITUDES': 'LLBTSOLICITUD',
    'CFVARIABLES': 'LLVARIABLE',
    'CTACCION': 'LLACCION',
    'CTACTOS': 'LLACTO',
    'CTCONDONACIONES': 'LLCONDONACION',
    'CTESTADOS': 'LLESTADO',
    'CTESTADOSACTO': 'LLESTDOACTO',
    'CTESTATUS': 'LLESTATUS',
    'CTESTATUSCARATULA': 'LLESTATUSCARATULA',
    'CTESTATUSFEDA': 'LLESTATUSFEDA',
    'CTFEDATARIOS': 'LLFEDATARIO'
}

# Foreing keys of every table ('table': ['fk_table': 'fk_column'])
foreing_keys = {
    'BTSOLICITUDES': [{'MVSOLICITUDES': 'LLSOLICITUD'},
                      {'CTUSUARIOS_202511281728': 'LLUSUARIO'},
                      {'CTESTATUS': 'LLESTATUS'}],
    # 'CFVARIABLES', 'CTACCION', 'CTACTOS', 'CTCONDONACIONES',
    # 'CTESTADOS', 'CTESTADOSACTO', 'CTESTATUS', 'CTESTATUSCARATULA'
    # 'CTESTATUSFEDA'
    'CTFEDATARIOS': [{'CTNACIONALIDADES': 'LLNACIONALIDAD'},
                     {'CTMUNICIPIOS': 'LLMUNICIPIO'},
                     {'CTESTADOS': 'LLESTADO'},
                     {'CTESTATUSFEDA': 'LLESTATUSFEDA'}]
}
