# globals.py
from pathlib import Path
# import polars as pl
from typing import Dict, List
import polars as pl
from pathlib import Path
from typing import Dict, List, Optional, Any

ROOT_PATH = Path(
    r"\\sia\AECF\DGATIC\LOTA\Bases de Datos\SIGER")

TABLES_TO_PROCESS = [
    'MVSOLICITUDES',
    # 'BTSOLICITUDES', 'CTACCION', 'CTACTOS', 'CTCONDONACIONES', 'CTESTADOS',
    # 'CTESTADOSACTO', 'CTESTATUS', 'CTESTATUSCARATULA', 'CTESTATUSFEDA',
    # 'CTFEDATARIOS', 'CTGIROS', 'CTMUNICIPIOS', 'CTNACIONALIDADES', 'CTSOCIOS',
    # 'CTTIPOSOCIEDAD', 'CTUSUARIOS_202511281728', 'DTCOMPSOCIOS', 'CFVARIABLES',
    # 'MVCARATULAS', 'MVFRMACTO', ''
]

# Tables with '"' inside the cells
quote_char_double_quotes = ['MVCARATULAS', 'MVFRMACTO', 'MVSOLICITUDES',
                            'CTUSUARIOS_202511281728', 'PAGO_PORTAL']

# Tables with encoding='utf8-lossy'
TABLES_UTF8 = ['CTUSUARIOS_202511281728', 'MVCARATULAS', 'MVSOLICITUDES']

# Columns to be dropped
col_drop = [
    'CRFME', 'DSANTREG', 'CFPAGODERECHOS_LLOFICINA', 'FULTLOGIN', 'DSCORREO',
    'FCNACIMIENTO', 'BLFOTO', 'DSADSCRIPCION', 'DSCONTRASENIA', 'DSACTO',
    'NOCONSECUTIVO', 'NORENGLON', 'NOMONTO', 'LLGRUPOTRABAJO', 'DSNOMBRERESPOFIC',
    'NOCONTINUIDAD', 'DSOBSERVACIONES', 'LLENTREGA', 'LLTIPOACLARACION',
    'LLPAGOSSINREG', 'LLSOLINSCRIPCION', 'LLSOLICITUD_2', 'LLPAGOSSRPETUSU',
    'FCLIMITESUBS', 'DSTELEFONO', 'DSFEA', 'DSMIMETYPEFOTO', 'FCREACTIVACION',
    'CRCODCONFIRMACION', 'DSJUSTIFICACION', 'NOINTLOGIN', 'DSTELCONTACTO',
    'FCACTUALIZCONTRAS', 'FCULTINTLOGIN', 'DSEXTENCION', 'FCINIOPERACION',
    'DSPAGINAWEB', 'LLPROCESO', 'FCALTA', 'DSREFERENCIARQ', 'NOTXCOUNTRQ',
    'DSCONCEPTORQ', 'DSRFCRQ', 'DSCLAVEMUNICIPIORQ', 'NOMOVIMIENTOSRQ',
    'DSACTORQ', 'DSDOMICILIORQ', 'DSENTIDADRQ', 'DSMUNICIPIORQ', 'DSCURP',
    'DSCPRQ', 'DSTELEFONORQ', 'DSIDNOTARIORQ', 'DSNOMBRENOTARIORQ', 'FCLIMITE',
    'DSRFCNOTARIORQ', 'DSTXIDRQ', 'DSNOMBRENOTARIORQ', 'DSFEDANETRQ',
    'DSTELEFONONOTARIORQ', 'DSMAILNOTARIORQ', 'DSCUENTARQ', 'DSPASSWORDRQ',
    'NOSERVICIOIDRQ', 'DSNOMBRERQ', 'DSAPELLIDOPATERNORQ', 'DSAPELLIDOMATERNORQ',
    'DSRAZONSOCIALRQ', 'DSTRAMITERQ', 'NOTXCOUNTRS', 'DSTIPOPAGORS',
    'DSCONCEPTORS', 'DSNOTARIORS', 'DSFOLIORS', 'FCTRANSACCIONRS', 'DSMOTIVO',
    'DSACTOCORTA', 'DSPAIS', 'DSCLAVEGIRO', 'NOCONSECUTIVO'
]

# Columns 'Int32' type for all tables
col_int32 = [
    'LLBTSOLICITUD', 'LLUSUARIO', 'LLGRUPOTRABAJO', 'LLESTATUS', 'LLPADRETIPSOC',
    'LLCARATULA', 'LLOFICINA', 'LLMUNICIPIO', 'LLSOCIO', 'LLESTADO', 'NONIVEL',
    'LLGIRO', 'LLTIPOSOCIEDAD', 'LLVARIABLE', 'LLNACIONALIDAD', 'LLESTATUSUSUA',
    'LLESTATUSCARATULA', 'LLPAGODERECHO', 'LLMVFRMACTO', 'LLSOLFRMPRE', 'LLCOMPSOCIOS',
    'LLESTDOACTO', 'LLFORMAACTO', 'LLVARACTO', 'LLTIPOSOLICITUD', 'LLFEDATARIO',
    'LLETAPA', 'LLCOMPFEDA', 'LLSOLICITUD', 'LLPAGO', 'LLACTO', 'LLMUNICIPIOADS',
    'LLESTATUSBANDEJA', 'LLUSOHORARIO', 'LLOFICINAMG', 'LLTIPOACTO', 'LLACCION',
    'LLCTFRMPRE', 'LLESTATUSFEDA', 'LLTIPOFEDATARIO', 'CRNUMERO', 'LLESTADOADS',
    'LLINFFRMPRE', 'LLESTDOACTOPRE', 'LLMVFRMACTOSUB',

]

# Columns 'Int8' type for all tables
col_int8 = ['BOMORAL', 'BOACERVO', 'BOACTIVO', 'BOVARIABLERANGO', 'BOANOTACIONACTIVA',
            'BOMIGRACION', 'BOINGRESO', 'BOINCIDENCIAS', 'BOPERNOSUBS', 'BOABREFOLIO',
            'BOVISIBLE', 'BOESFEDATARIO']

# Columns 'DATE' type for all tables
col_date = ['FCETAPA', 'FCAPERTURA', 'FCNACIMIENTO',
            'FULTLOGIN', 'FCALTA', 'FCTRANSACCIONRS']

# String Columns to be converted to string, to be clean and to be converted to uppercase
col_str = ['DSDENSOCIAL', 'DSDIRECCION', 'DSDURACION', 'DSNOMBRESOCIO', 'DSRFC',
           'DSGIRO', 'DSTIPOSOCIEDAD', 'DSOBJETO', 'DSAPELLIDOPATERNO', 'DSESTADO',
           'DSNACIONALIDAD', 'DSAPELLIDOMATERNO', 'DSNOMBREVARIABLE', 'DSCODIGO',
           'DSDESCRIPCION', 'DSNOMBRE', 'DSOFICINA', 'DSMUNICIPIO', 'DSACTO', 'DSSERIE',
           'DSACCION', 'DSNOMBRECOND', 'DSESTADOACTO', 'DSESTATUS', 'DSABREVSTATUS',
           'FCMODIFICACION', 'FCCONSTITUCION', 'DSDOMICILIO', 'FCINGRESO',
           'FCINSCRIPCION']
